### ISSUE TITLE
A minor issue

### ISSUE THREAD

**Issue by xchray** [jannopet/LEGO-WeDo-2.0-Python-SDK#3]
I have a connection issue. It turned out that in my environment too many devices which have stronger signal than wedo2 motor, even wedo2 is very close to my computer. So I made a workaround below. 

Is there any better way to determine wedo2 motor? 
Thanks, 
Ray

class Smarthub:

    def __init__(self, dev_addr = None):

        device_address = dev_addr
        if device_address == None:
            devices = adapter.scan(1)
            devices = sorted(devices, key=lambda k: k['rssi'], reverse=True)
            device_address = devices[0]['address']

    from wedo2.smarthub import Smarthub    
    hub = Smarthub('xx.xx.xx.xx.xx')
    hub.turn_motor(80)

**Comment by AntoniLuongPham** [comment]
Hi @xchray,

I am also trying to use this Python library to connect to my WeDo2 hub, but I keep having this error when initializing `hub = Smarthub()`:

`raise NotConnectedError("Unable to reconnect with USB "`
`pygatt.exceptions.NotConnectedError: Unable to reconnect with USB device after rebooting`

I have create an issue [here](https://github.com/jannopet/LEGO-WeDo-2.0-Python-SDK/issues/4), but while waiting for the author to reply, may I check if you are still able to connect to your WeDo2 using your workaround above? If your method still works, I would like to try out on my end.

Thank you so much, @xchray!

Antoni

**Comment by xchray** [comment]
Hi, 

I changed below part of the code. 


class Smarthub:
    def __init__(self, dev_addr = None):        global adapter        if adapter is None:            adapter = _Patched_BGAPIBackend()            adapter.start()
        self.io = None        self.service_manager = None        self.device = None
        device_address = dev_addr        if device_address == None:            devices = adapter.scan(1)            devices = sorted(devices, key=lambda k: k['rssi'], reverse=True)            device_address = devices[0]['address']
and then i find out the mac address in debug mode of wedo motor and passing address explicitly. 
# hub = Smarthub('04:EE:03:17:DE:C8')# print('Hub connected')# hub.turn_motor(80)# print('Hub is working')# sleep(30)# hub.disconnect()# print('Hub is disconnected')
Hope this helps. Regards, 
Xin    On Thursday, August 12, 2021, 05:23:54 AM GMT+2, Antoni Lương-Phạm Anh Quân ***@***.***> wrote:  
 
 


Hi @xchray,

I am also trying to use this Python library to connect to my WeDo2 hub, but I keep having this error when initializing hub = Smarthub():

raise NotConnectedError("Unable to reconnect with USB "
pygatt.exceptions.NotConnectedError: Unable to reconnect with USB device after rebooting

I have create an issue here, but while waiting for the author to reply, may I check if you are still able to connect to your WeDo2 using your workaround above? If your method still works, I would like to try out on my end.

Thank you so much, @xchray!

Antoni

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xchray** [comment]
> Hi @xchray,
> 
> I am also trying to use this Python library to connect to my WeDo2 hub, but I keep having this error when initializing `hub = Smarthub()`:
> 
> `raise NotConnectedError("Unable to reconnect with USB "`
> `pygatt.exceptions.NotConnectedError: Unable to reconnect with USB device after rebooting`
> 
> I have create an issue [here](https://github.com/jannopet/LEGO-WeDo-2.0-Python-SDK/issues/4), but while waiting for the author to reply, may I check if you are still able to connect to your WeDo2 using your workaround above? If your method still works, I would like to try out on my end.
> 
> Thank you so much, @xchray!
> 
> Antoni

I changed below code, and then calling 

class Smarthub:
    def __init__(self, **dev_addr = None**): ->changed by me
...
        **device_address = dev_addr ->added by me
        if device_address == None:** ->added by me
            devices = adapter.scan(1)
            devices = sorted(devices, key=lambda k: k['rssi'], reverse=True)
            device_address = devices[0]['address']


and then calling it using my wedo2 mac address directly. i got wedo2 mac addr in debug mode. 
     hub = Smarthub('xx:xx:xx:xx:xx:xx')
     print('Hub connected')
     hub.turn_motor(80)

**Comment by AntoniLuongPham** [comment]
Hi @xchray,

Thank you so much for your reply!

May I ask how you got the MAC address in the debug mode? Are you using Windows or MacOS?

I use Mac and when I go into **System Preferences >> Bluetooth** I don't see the WeDo2 hub listed in the detected devices when that hub is turned on.

Antoni

**Comment by xchray** [comment]
set debug point below, you should see your wedo2 engine in "devices" list. 
Xin

class Smarthub:

    def __init__(self, dev_addr = None):
        global adapter
        if adapter is None:
            adapter = _Patched_BGAPIBackend()
            adapter.start()

        self.io = None
        self.service_manager = None
        self.device = None

        device_address = dev_addr
        if device_address == None:
            devices = adapter.scan(1)
            devices = sorted(devices, key=lambda k: k['rssi'], reverse=True) **-> ADD DEBUG POINT THIS LINE**
            device_address = devices[0]['address']

**Comment by AntoniLuongPham** [comment]
Hi @xchray:

May I ask you some more? I still have trouble with connecting to the WeDo2 Hub.

My modified WeDo2 smarthub.py code has the following:

```
        if device_address is None:
            devices = adapter.scan(1)
            print(f'DEVICES before sorting: {devices}')
            devices = sorted(devices, key=lambda k: k['rssi'], reverse=True)
            print(f'DEVICES after sorting: {devices}')
            device_address = devices[0]['address']
```

And my main program is:

```
from wedo2.smarthub import Smarthub

hub = Smarthub()
```

However I still have the same error as before:

```
Traceback (most recent call last):
    hub = Smarthub()
  File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/wedo2/smarthub.py", line 21, in __init__
    adapter.start()
  File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/pygatt/backends/bgapi/bgapi.py", line 178, in start
    self._open_serial_port()
  File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/wedo2/smarthub.py", line 357, in _open_serial_port
    raise NotConnectedError("Unable to reconnect with USB "
pygatt.exceptions.NotConnectedError: Unable to reconnect with USB device after rebooting
```

So it seems the program fails at `devices = adapter.scan(1)`, before the debugging point.

May I ask if this method still works with your WeDo2 hub today?

Thank you very much @xchray!

Antoni

**Comment by BekaMaster** [comment]
> Hi @xchray:
> 
> May I ask you some more? I still have trouble with connecting to the WeDo2 Hub.
> 
> My modified WeDo2 smarthub.py code has the following:
> 
> ```
>         if device_address is None:
>             devices = adapter.scan(1)
>             print(f'DEVICES before sorting: {devices}')
>             devices = sorted(devices, key=lambda k: k['rssi'], reverse=True)
>             print(f'DEVICES after sorting: {devices}')
>             device_address = devices[0]['address']
> ```
> 
> And my main program is:
> 
> ```
> from wedo2.smarthub import Smarthub
> 
> hub = Smarthub()
> ```
> 
> However I still have the same error as before:
> 
> ```
> Traceback (most recent call last):
>     hub = Smarthub()
>   File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/wedo2/smarthub.py", line 21, in __init__
>     adapter.start()
>   File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/pygatt/backends/bgapi/bgapi.py", line 178, in start
>     self._open_serial_port()
>   File "/Users/vinh/Library/Python/3.9/lib/python/site-packages/wedo2/smarthub.py", line 357, in _open_serial_port
>     raise NotConnectedError("Unable to reconnect with USB "
> pygatt.exceptions.NotConnectedError: Unable to reconnect with USB device after rebooting
> ```
> 
> So it seems the program fails at `devices = adapter.scan(1)`, before the debugging point.
> 
> May I ask if this method still works with your WeDo2 hub today?
> 
> Thank you very much @xchray!
> 
> Antoni

I've got the same issue, I use Windows 10.
Somebody can help with this?
